---
- name: Ensure nzbget is installed
  apt: pkg=nzbget state=installed
- name: Ensure user group for the applications exists
  group: name={{ user_group }} state=present
- name: Ensure nzbget user is present
  user: name={{ user }} group={{ user_group }}
        home={{ nzbget_home }} state=present comment="nzbget"
- name: Ensure nzbget download dir exists
  file: path={{ usenet_download_dir }} state=directory
        owner={{ user }} group={{ user_group }} mode=0775
- name: Ensure permissions for nzbget home are set correctly
  file: path={{ nzbget_home }}
        owner={{ user }} group={{ user_group }}
        state=directory recurse=yes mode=0775
- name: Install nzbget config
  template: src=nzbget.conf.j2 dest={{ nzbget_conf }}
            owner={{ user}} group={{ user_group }} mode=0644
- name: Install nzbget upstart script
  template: src=nzbget.upstart.conf.j2 dest=/etc/init/nzbget.conf
- name: Ensure nzbget is running
  service: name=nzbget state=started
